services:
  - type: web
    name: ipt-final-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      # Database credentials
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_USER
        value: u875409848_villanueva
      - key: DB_PASSWORD
        value: 9T2Z5$3UKkgSYzE
      - key: DB_NAME
        value: u875409848_villanueva
      - key: DB_PORT
        value: 3306
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true 